//! Regression coverage for malformed / real-world-broken input (issue #4).
//!
//! Every fixture used here is deliberately invalid — a real-world-broken
//! export, an RFC violation, or a fuzzer-found edge case — and is excluded
//! from the blanket "must parse successfully" fixture tests generated by
//! `build.rs` (see `MALFORMED_FIXTURES` there). Each test below pins down a
//! *specific* outcome for its fixture (an `Err` variant, or — for
//! `empty_RDATE.ics` — a specific non-data-loss `Ok`) rather than merely
//! "doesn't panic": per the issue, a panic on malformed input is always a
//! bug, since `Calendar::parse` is documented to return `Result`, never to
//! abort the process.
//!
//! `CalendarParseError`'s `Lexer`/`Parse` payload types
//! (`ast::LexerError`/`ast::parser::ParseError`) aren't publicly reachable
//! (the `ast` module is `pub(crate)`), so these tests match the outer
//! variant with `_` rather than the inner error detail — the same
//! constraint the crate's own public API imposes on any downstream user.

use icalendar::{Calendar, CalendarParseError, Component};

fn fixture(name: &str) -> Vec<u8> {
    let path = format!(
        "{}/tests/fixtures/collective-icalendar/calendars/{name}",
        env!("CARGO_MANIFEST_DIR")
    );
    std::fs::read(&path)
        .unwrap_or_else(|e| panic!("fixture {name} should be readable: {e}"))
}

/// `DTSTART;;VALUE=DATE-TIME:...` — a doubled `;` in the parameter list.
/// Must be rejected as a parse error, not silently accepted with a mangled
/// `DTSTART` or a misaligned param list.
#[test]
fn doubled_semicolon_in_param_list_is_a_parse_error() {
    let bytes = fixture("broken_ical.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// `DTSTART:INVALID-DATE` — a non-numeric date-time literal.
#[test]
fn non_numeric_dtstart_is_a_parse_error() {
    let bytes = fixture("broken_dtstart.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Both `DTSTART` and `DTEND` are garbage. Confirms the first bad value
/// short-circuits parsing rather than deferring to `build()` and reporting
/// something misleading about `DTEND`/`DTSTART` mutual consistency instead.
#[test]
fn garbage_dtstart_and_dtend_is_a_parse_error() {
    let bytes = fixture("issue_1081_invalid_start_and_end.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// `DURATION:P999999999999999999W` — the week count overflows every
/// representable `chrono::TimeDelta`. This used to panic (`TimeDelta::weeks
/// out of bounds`, `Duration::try_from` in `src/values.rs` used the
/// panicking `ChronoDuration::weeks`/`days`/`hours`/`minutes`/`seconds`
/// constructors and unchecked `+=`); it must instead surface as an
/// ordinary `Err`. If this regresses to a panic, this test fails via that
/// panic rather than a clean assertion, which is the point.
#[test]
fn duration_week_overflow_is_a_parse_error_not_a_panic() {
    let bytes = fixture("invalid_duration.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// `RRULE:FREQ=INVALID_TYPE_CAUSES_ERROR` — an unrecognized `FREQ` token.
/// Existing `Recur` tests only cover valid `FREQ` values and one
/// out-of-range `BYSECOND`; nothing previously exercised a bad `FREQ` itself.
#[test]
fn unrecognized_rrule_freq_is_a_parse_error() {
    let bytes = fixture("issue_1081_invalid_rrule_freq.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Seven consecutive empty `RDATE:` values, nested inside a `DAYLIGHT`
/// block that (per RFC 5545 §3.6.5) is only legal *inside* a `VTIMEZONE`,
/// not directly under `VCALENDAR`. Per issue #13, an unrecognized top-level
/// component is tolerated and preserved verbatim rather than erroring or
/// silently dropping data — so this parses `Ok`, with the whole `DAYLIGHT`
/// block (RDATE lines included) captured as a `Component::Unknown` rather
/// than being routed through (and value-validated by) the typed `RDATE`
/// property parser.
#[test]
fn empty_rdate_under_unwrapped_daylight_is_preserved_verbatim() {
    let bytes = fixture("empty_RDATE.ics");
    let cal = Calendar::parse(&bytes)
        .expect("unrecognized top-level component must not be a hard error");
    assert_eq!(cal.components().len(), 1);
    match &cal.components()[0] {
        Component::Unknown(unknown) => {
            assert_eq!(unknown.name(), "DAYLIGHT");
            let rdate_lines = unknown
                .lines()
                .iter()
                .filter(|l| l.starts_with("RDATE"))
                .count();
            assert_eq!(
                rdate_lines, 7,
                "all seven empty RDATE lines must be preserved, not dropped"
            );
        }
        other => panic!("expected Component::Unknown(DAYLIGHT), got {other:?}"),
    }
}

/// A leading UTF-8 BOM (`EF BB BF`) before `BEGIN:VCALENDAR`. No BOM
/// stripping exists in `src/ast/lexer.rs`, so the BOM bytes corrupt the
/// `BEGIN` keyword match. Documents the current behavior (a lexer error,
/// not a panic or a silent empty calendar) — RFC 5545 doesn't mandate BOM
/// handling either way, so this pins down today's contract rather than
/// asserting it's the ideal one.
#[test]
fn leading_bom_is_a_lexer_error() {
    let bytes = fixture("bom_calendar.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Lexer(_))
    ));
}

/// A `VCALENDAR` truncated mid-object — twenty empty `VEVENT`s but no
/// closing `END:VCALENDAR` at all.
#[test]
fn truncated_calendar_with_many_events_is_a_parse_error() {
    let bytes = fixture("big_bad_calendar.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Same shape as `big_bad_calendar.ics`, minimal: one empty `VEVENT`, no
/// closing `END:VCALENDAR`.
#[test]
fn truncated_calendar_single_event_is_a_parse_error() {
    let bytes = fixture("small_bad_calendar.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A real-world Google Calendar export where the second of two `VEVENT`s
/// has `EXDATE;VALUE=DATE:` with an empty value.
#[test]
fn empty_exdate_value_is_a_parse_error() {
    let bytes = fixture("parsing_error.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// `TZOFFSETFROM`/`TZOFFSETTO:+5744` — not a valid UTC offset (57 hours, 44
/// minutes exceeds any real zone offset and isn't representable per RFC
/// 5545 §3.3.14's own `+/-((00-13)(00-59)|(14)(00))` shape).
#[test]
fn out_of_range_utc_offset_is_a_parse_error() {
    let bytes = fixture("parsing_error_in_UTC_offset.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A zero-length top-level component name (`BeGIN:` followed by a NUL
/// byte), from the upstream Python parser's fuzz corpus. Must not panic on
/// the zero-length/non-UTF8-adjacent name.
#[test]
fn zero_length_component_name_does_not_panic() {
    let bytes = fixture("fuzz_testcase_0_char_in_component_name.ics");
    assert!(Calendar::parse(&bytes).is_err());
}

/// `BEGIN:V` (not any real component keyword) followed by a bare, dangling
/// `RRULE` line and no closing `END`. From the upstream fuzz corpus.
#[test]
fn invalid_month_fuzz_case_does_not_panic() {
    let bytes = fixture("fuzz_testcase_invalid_month.ics");
    assert!(Calendar::parse(&bytes).is_err());
}

/// A lone `CR` (not part of a `CRLF` pair) embedded mid-line inside a
/// `VTIMEZONE`'s `TZID` value. The lexer requires `CR` to always be
/// followed by `LF`; a lone `CR` must be a lexer error, not an infinite
/// loop or a panic.
#[test]
fn lone_cr_inside_vtimezone_is_a_lexer_error() {
    let bytes = fixture("fuzz_testcase_vtimezone_lone_cr.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Lexer(_))
    ));
}
