//! Regression coverage for malformed / real-world-broken input (issue #4),
//! plus genuinely RFC 5545-invalid fixtures more broadly (issue #27).
//!
//! Every fixture used here is deliberately invalid — a real-world-broken
//! export, an RFC violation, or a fuzzer-found edge case — and is excluded
//! from the blanket "must parse successfully" fixture tests generated by
//! `build.rs` (see `MALFORMED_FIXTURES` there). Each test below pins down a
//! *specific* outcome for its fixture (an `Err` variant, or — for
//! `empty_RDATE.ics` — a specific non-data-loss `Ok`) rather than merely
//! "doesn't panic": per the issue, a panic on malformed input is always a
//! bug, since `Calendar::parse` is documented to return `Result`, never to
//! abort the process.
//!
//! The issue #27 bucket-2 tests further down this file cover fixtures that
//! are real-world exports or hand-authored test fixtures which happen to
//! skip a required property (`DTSTAMP`/`PRODID`/`DTSTART`), have zero
//! components under `VCALENDAR`, or are otherwise grammatically invalid —
//! `Calendar::parse` returning `Err` is correct per RFC 5545, even though
//! real-world producers often emit exactly this shape.
//!
//! `CalendarParseError`'s `Lexer`/`Parse` payload types
//! (`ast::LexerError`/`ast::parser::ParseError`) aren't publicly reachable
//! (the `ast` module is `pub(crate)`), so these tests match the outer
//! variant with `_` rather than the inner error detail — the same
//! constraint the crate's own public API imposes on any downstream user.

use cratical::{Calendar, CalendarParseError, Component};

fn fixture(name: &str) -> Vec<u8> {
    let path = format!(
        "{}/tests/fixtures/collective-icalendar/calendars/{name}",
        env!("CARGO_MANIFEST_DIR")
    );
    std::fs::read(&path)
        .unwrap_or_else(|e| panic!("fixture {name} should be readable: {e}"))
}

/// `DTSTART;;VALUE=DATE-TIME:...` — a doubled `;` in the parameter list.
/// Must be rejected as a parse error, not silently accepted with a mangled
/// `DTSTART` or a misaligned param list.
#[test]
fn doubled_semicolon_in_param_list_is_a_parse_error() {
    let bytes = fixture("broken_ical.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// `DTSTART:INVALID-DATE` — a non-numeric date-time literal.
#[test]
fn non_numeric_dtstart_is_a_parse_error() {
    let bytes = fixture("broken_dtstart.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Both `DTSTART` and `DTEND` are garbage. Confirms the first bad value
/// short-circuits parsing rather than deferring to `build()` and reporting
/// something misleading about `DTEND`/`DTSTART` mutual consistency instead.
#[test]
fn garbage_dtstart_and_dtend_is_a_parse_error() {
    let bytes = fixture("issue_1081_invalid_start_and_end.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// `DURATION:P999999999999999999W` — the week count overflows every
/// representable `chrono::TimeDelta`. This used to panic (`TimeDelta::weeks
/// out of bounds`, `Duration::try_from` in `src/values.rs` used the
/// panicking `ChronoDuration::weeks`/`days`/`hours`/`minutes`/`seconds`
/// constructors and unchecked `+=`); it must instead surface as an
/// ordinary `Err`. If this regresses to a panic, this test fails via that
/// panic rather than a clean assertion, which is the point.
#[test]
fn duration_week_overflow_is_a_parse_error_not_a_panic() {
    let bytes = fixture("invalid_duration.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// `RRULE:FREQ=INVALID_TYPE_CAUSES_ERROR` — an unrecognized `FREQ` token.
/// Existing `Recur` tests only cover valid `FREQ` values and one
/// out-of-range `BYSECOND`; nothing previously exercised a bad `FREQ` itself.
#[test]
fn unrecognized_rrule_freq_is_a_parse_error() {
    let bytes = fixture("issue_1081_invalid_rrule_freq.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Seven consecutive empty `RDATE:` values, nested inside a `DAYLIGHT`
/// block that (per RFC 5545 §3.6.5) is only legal *inside* a `VTIMEZONE`,
/// not directly under `VCALENDAR`. Per issue #13, an unrecognized top-level
/// component is tolerated and preserved verbatim rather than erroring or
/// silently dropping data — so this parses `Ok`, with the whole `DAYLIGHT`
/// block (RDATE lines included) captured as a `Component::Unknown` rather
/// than being routed through (and value-validated by) the typed `RDATE`
/// property parser.
#[test]
fn empty_rdate_under_unwrapped_daylight_is_preserved_verbatim() {
    let bytes = fixture("empty_RDATE.ics");
    let cal = Calendar::parse(&bytes)
        .expect("unrecognized top-level component must not be a hard error");
    assert_eq!(cal.components().len(), 1);
    match &cal.components()[0] {
        Component::Unknown(unknown) => {
            assert_eq!(unknown.name(), "DAYLIGHT");
            let rdate_lines = unknown
                .lines()
                .iter()
                .filter(|l| l.starts_with("RDATE"))
                .count();
            assert_eq!(
                rdate_lines, 7,
                "all seven empty RDATE lines must be preserved, not dropped"
            );
        }
        other => panic!("expected Component::Unknown(DAYLIGHT), got {other:?}"),
    }
}

/// A leading UTF-8 BOM (`EF BB BF`) before `BEGIN:VCALENDAR`. Per issue
/// #15, `Lexer::new` now strips a leading BOM before scanning, so this no
/// longer corrupts the `BEGIN` keyword match. The fixture itself is still
/// an otherwise-minimal, invalid calendar (no `PRODID`/`VERSION`/
/// component), so parsing still fails overall — but now for that
/// documented reason, as an ordinary `Parse` error, not a `Lexer` error
/// caused by the BOM bytes themselves.
#[test]
fn leading_bom_is_stripped_and_no_longer_corrupts_parsing() {
    let bytes = fixture("bom_calendar.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A `VCALENDAR` truncated mid-object — twenty empty `VEVENT`s but no
/// closing `END:VCALENDAR` at all.
#[test]
fn truncated_calendar_with_many_events_is_a_parse_error() {
    let bytes = fixture("big_bad_calendar.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Same shape as `big_bad_calendar.ics`, minimal: one empty `VEVENT`, no
/// closing `END:VCALENDAR`.
#[test]
fn truncated_calendar_single_event_is_a_parse_error() {
    let bytes = fixture("small_bad_calendar.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A real-world Google Calendar export where the second of two `VEVENT`s
/// has `EXDATE;VALUE=DATE:` with an empty value.
#[test]
fn empty_exdate_value_is_a_parse_error() {
    let bytes = fixture("parsing_error.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// `TZOFFSETFROM`/`TZOFFSETTO:+5744` — not a valid UTC offset (57 hours, 44
/// minutes exceeds any real zone offset and isn't representable per RFC
/// 5545 §3.3.14's own `+/-((00-13)(00-59)|(14)(00))` shape).
#[test]
fn out_of_range_utc_offset_is_a_parse_error() {
    let bytes = fixture("parsing_error_in_UTC_offset.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A zero-length top-level component name (`BeGIN:` followed by a NUL
/// byte), from the upstream Python parser's fuzz corpus. Must not panic on
/// the zero-length/non-UTF8-adjacent name.
#[test]
fn zero_length_component_name_does_not_panic() {
    let bytes = fixture("fuzz_testcase_0_char_in_component_name.ics");
    assert!(Calendar::parse(&bytes).is_err());
}

/// `BEGIN:V` (not any real component keyword) followed by a bare, dangling
/// `RRULE` line and no closing `END`. From the upstream fuzz corpus.
#[test]
fn invalid_month_fuzz_case_does_not_panic() {
    let bytes = fixture("fuzz_testcase_invalid_month.ics");
    assert!(Calendar::parse(&bytes).is_err());
}

/// A lone `CR` (not part of a `CRLF` pair) embedded mid-line inside a
/// `VTIMEZONE`'s `TZID` value. The lexer requires `CR` to always be
/// followed by `LF`; a lone `CR` must be a lexer error, not an infinite
/// loop or a panic.
#[test]
fn lone_cr_inside_vtimezone_is_a_lexer_error() {
    let bytes = fixture("fuzz_testcase_vtimezone_lone_cr.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Lexer(_))
    ));
}

/// `REFRESH - INTERVAL; VALUE = DURATION:PT48H` — stray spaces around the
/// hyphen in the property name and around the param `=` (issue #8, gap 7).
/// The lexer's `name_chars()` only consumes `ALPHA`/`DIGIT`/`-`, so it stops
/// at the first space: the token name is just `REFRESH`, leaving
/// `" - INTERVAL; VALUE = DURATION:PT48H"` as the raw remainder handed to
/// the `Iana` fallback (`REFRESH` isn't `X-`-prefixed and has no
/// `PROPERTY_DISPATCH` entry). That remainder's first param segment,
/// `" - INTERVAL"`, has no `=`, so it fails at `SharedParams` parsing
/// rather than silently truncating to a bare `REFRESH` property or
/// stitching `INTERVAL` back on — this producer's whitespace quirk is
/// rejected outright, not tolerated.
#[test]
fn whitespace_around_property_and_param_names_is_a_parse_error() {
    let bytes = fixture("issue_351_whitespace_in_property_and_params.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

// --- issue #27 bucket 2: genuinely RFC 5545-invalid content ---
//
// Every fixture below is a real-world export or hand-authored test fixture
// that skips a required property, has zero components, or is otherwise
// grammatically invalid per RFC 5545 — `Calendar::parse` returning `Err` is
// correct behavior for each, same philosophy as the fixtures above.

fn fixture_at(rel: &str) -> Vec<u8> {
    let path = format!("{}/tests/fixtures/{rel}", env!("CARGO_MANIFEST_DIR"));
    std::fs::read(&path)
        .unwrap_or_else(|e| panic!("fixture {rel} should be readable: {e}"))
}

// Missing `DTSTAMP` (REQUIRED, RFC 5545 §3.6.1 etc.).

/// Missing DTSTAMP (REQUIRED, RFC 5545 §3.6.1) on its VEVENT.
#[test]
fn dtstamp_missing_created_calendar_with_unicode_fields() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/created_calendar_with_unicode_fields.\
         ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing DTSTAMP (REQUIRED, §3.6.1) on its VEVENT.
#[test]
fn dtstamp_missing_example() {
    let bytes = fixture_at("collective-icalendar/calendars/example.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing DTSTAMP on its components (REQUIRED, §3.6.1/§3.6.2).
#[test]
fn dtstamp_missing_issue_1050_calendar_with_events_and_todos() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/\
         issue_1050_calendar_with_events_and_todos.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing DTSTAMP (REQUIRED, §3.6.1).
#[test]
fn dtstamp_missing_issue_1050_forward_timezone_reference() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/issue_1050_forward_timezone_reference.\
         ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing DTSTAMP (REQUIRED, §3.6.1).
#[test]
fn dtstamp_missing_issue_1050_simple_calendar() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/issue_1050_simple_calendar.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing DTSTAMP (REQUIRED, §3.6.1) alongside an RRULE.
#[test]
fn dtstamp_missing_issue_1081_event_with_rrule() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/issue_1081_event_with_rrule.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing DTSTAMP (REQUIRED, §3.6.1).
#[test]
fn dtstamp_missing_issue_1081_list_of_properties() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/issue_1081_list_of_properties.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing DTSTAMP (REQUIRED, §3.6.1).
#[test]
fn dtstamp_missing_issue_1081_tzid_param() {
    let bytes =
        fixture_at("collective-icalendar/calendars/issue_1081_tzid_param.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing DTSTAMP (REQUIRED, §3.6.1) on a recurring VEVENT.
#[test]
fn dtstamp_missing_issue_1231_recurrence() {
    let bytes =
        fixture_at("collective-icalendar/calendars/issue_1231_recurrence.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing DTSTAMP (REQUIRED, §3.6.1).
#[test]
fn dtstamp_missing_issue_1426() {
    let bytes = fixture_at("collective-icalendar/calendars/issue_1426.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing DTSTAMP (REQUIRED, §3.6.1).
#[test]
fn dtstamp_missing_issue_1426_value_parameters() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/issue_1426_value_parameters.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing DTSTAMP (REQUIRED, §3.6.1) — the libical suite's core RFC 2445-era
/// regression fixture.
#[test]
fn dtstamp_missing_2445() {
    let bytes = fixture_at("libical/2445.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing DTSTAMP (REQUIRED, §3.6.1) on one of its many VEVENTs.
#[test]
fn dtstamp_missing_large() {
    let bytes = fixture_at("libical/large.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

// Missing `PRODID` (REQUIRED at `VCALENDAR` level, §3.4).

/// Missing PRODID (REQUIRED at VCALENDAR level, §3.4).
#[test]
fn prodid_missing_issue_168_expected_output() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/issue_168_expected_output.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing PRODID (REQUIRED, §3.4).
#[test]
fn prodid_missing_issue_178_custom_component_inside_other() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/\
         issue_178_custom_component_inside_other.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing PRODID (REQUIRED, §3.4).
#[test]
fn prodid_missing_issue_322_expected_calendar() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/issue_322_expected_calendar.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing PRODID (REQUIRED, §3.4).
#[test]
fn prodid_missing_issue_722_missing_timezones() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/issue_722_missing_timezones.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing PRODID (REQUIRED, §3.4).
#[test]
fn prodid_missing_issue_798_freebusy() {
    let bytes =
        fixture_at("collective-icalendar/calendars/issue_798_freebusy.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing PRODID (REQUIRED, §3.4).
#[test]
fn prodid_missing_issue_798_related_to() {
    let bytes =
        fixture_at("collective-icalendar/calendars/issue_798_related_to.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing PRODID (REQUIRED, §3.4).
#[test]
fn prodid_missing_period_with_timezone() {
    let bytes =
        fixture_at("collective-icalendar/calendars/period_with_timezone.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing PRODID (REQUIRED, §3.4) — a bare RDATE example lifted from the RFC
/// text.
#[test]
fn prodid_missing_rfc_5545_rdate_example() {
    let bytes =
        fixture_at("collective-icalendar/calendars/rfc_5545_RDATE_example.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing PRODID (REQUIRED, §3.4).
#[test]
fn prodid_missing_rfc_6868() {
    let bytes = fixture_at("collective-icalendar/calendars/rfc_6868.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing PRODID (REQUIRED, §3.4).
#[test]
fn prodid_missing_rfc_7256_multi_value_parameters() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/rfc_7256_multi_value_parameters.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing PRODID (REQUIRED, §3.4).
#[test]
fn prodid_missing_rfc_7986_conferences() {
    let bytes =
        fixture_at("collective-icalendar/calendars/rfc_7986_conferences.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing PRODID (REQUIRED, §3.4).
#[test]
fn prodid_missing_rfc_7986_image() {
    let bytes = fixture_at("collective-icalendar/calendars/rfc_7986_image.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing PRODID (REQUIRED, §3.4).
#[test]
fn prodid_missing_smallcluster() {
    let bytes = fixture_at("libical/smallcluster.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

// Missing `DTSTART` — none of these set a calendar-level `METHOD`, so per
// §3.6.1's grammar `DTSTART` is REQUIRED (it's only optional when `METHOD` is
// present).

/// Missing DTSTART on a VEVENT with no calendar-level METHOD set, so per
/// §3.6.1's grammar DTSTART is REQUIRED (it's only optional when METHOD is
/// present).
#[test]
fn dtstart_missing_issue_1050_multiple_calendars() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/issue_1050_multiple_calendars.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing DTSTART, no calendar-level METHOD (REQUIRED per §3.6.1).
#[test]
fn dtstart_missing_issue_1050_uid_in_description() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/issue_1050_uid_in_description.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing DTSTART, no calendar-level METHOD (REQUIRED per §3.6.1).
#[test]
fn dtstart_missing_issue_1081_with_summary() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/issue_1081_with_summary.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing DTSTART, no calendar-level METHOD (REQUIRED per §3.6.1).
#[test]
fn dtstart_missing_issue_1549_binary_attachment() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/issue_1549_binary_attachment.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing DTSTART, no calendar-level METHOD (REQUIRED per §3.6.1).
#[test]
fn dtstart_missing_rfc_9253_gap() {
    let bytes = fixture_at("collective-icalendar/calendars/rfc_9253_gap.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing DTSTART, no calendar-level METHOD (REQUIRED per §3.6.1).
#[test]
fn dtstart_missing_rfc_9253_related_to() {
    let bytes =
        fixture_at("collective-icalendar/calendars/rfc_9253_related_to.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

// "Premature end of input": an empty `RDATE:` value, a `FREEBUSY`/`RDATE`
// `PERIOD` using bare `DATE` instead of the required `DATE-TIME` on both sides,
// a truncated `DATE-TIME` missing its seconds component, or (`restriction.ics`)
// deliberately duplicated singleton properties.

/// An empty RDATE: value — the grammar requires >=1 rdtval.
#[test]
fn premature_end_issue_1081_empty_rdate() {
    let bytes =
        fixture_at("collective-icalendar/calendars/issue_1081_empty_rdate.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A FREEBUSY PERIOD value using bare DATE instead of the required DATE-TIME on
/// both sides (e.g. `19970101/19970102`).
#[test]
fn premature_end_issue_1633_freebusy_with_dates() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/issue_1633_freebusy_with_dates.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// An RDATE PERIOD value using bare DATE instead of the required DATE-TIME on
/// both sides.
#[test]
fn premature_end_issue_1633_rdate_with_dates() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/issue_1633_rdate_with_dates.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// An RDATE PERIOD value using bare DATE instead of the required DATE-TIME on
/// both sides, with a TZID param present.
#[test]
fn premature_end_issue_1633_rdate_with_dates_and_tzid() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/issue_1633_rdate_with_dates_and_tzid.\
         ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A truncated DATE-TIME missing its seconds component (e.g. `19970901T1300Z`
/// instead of `T130000Z`).
#[test]
fn premature_end_2() {
    let bytes = fixture_at("libical/2.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A truncated DATE-TIME missing its seconds component.
#[test]
fn premature_end_process_calendar() {
    let bytes = fixture_at("libical/process-calendar.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A truncated DATE-TIME missing its seconds component.
#[test]
fn premature_end_process_incoming() {
    let bytes = fixture_at("libical/process-incoming.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Deliberately duplicates singleton properties (RECURRENCE-ID, SEQUENCE,
/// CATEGORIES, CLASS each appear twice) — reads like a purpose-built
/// cardinality-restriction violation test.
#[test]
fn premature_end_restriction() {
    let bytes = fixture_at("libical/restriction.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

// Zero components under `VCALENDAR` (the grammar requires `component =
// 1*(eventc/todoc/...)`), or a malformed `VCALENDAR` closing (trailing garbage,
// missing `END`).

/// Zero components under VCALENDAR — the grammar requires component =
/// 1*(eventc/todoc/...).
#[test]
fn zero_components_calendar_with_unicode() {
    let bytes =
        fixture_at("collective-icalendar/calendars/calendar_with_unicode.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Zero components under VCALENDAR, only calendar-level properties.
#[test]
fn zero_components_empty() {
    let bytes = fixture_at("collective-icalendar/calendars/empty.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare garbage `X` line after END:VEVENT, so the calendar fails to close
/// cleanly.
#[test]
fn zero_components_issue_104_broken_calendar() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/issue_104_broken_calendar.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Zero components under VCALENDAR.
#[test]
fn zero_components_issue_1050_empty_calendar() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/issue_1050_empty_calendar.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Zero components under VCALENDAR.
#[test]
fn zero_components_issue_1238() {
    let bytes = fixture_at("collective-icalendar/calendars/issue_1238.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing END:VCALENDAR entirely.
#[test]
fn zero_components_pr_480_summary_with_colon() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/pr_480_summary_with_colon.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Zero components under VCALENDAR — a bare RFC 7265 calprops excerpt.
#[test]
fn zero_components_rfc_7265_example_1() {
    let bytes =
        fixture_at("collective-icalendar/calendars/rfc_7265_example_1.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Zero components under VCALENDAR — a fully RFC 7986-correct set of
/// calendar-level properties is still invalid on its own without >=1 component.
#[test]
fn zero_components_rfc_7986_properties() {
    let bytes =
        fixture_at("collective-icalendar/calendars/rfc_7986_properties.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Zero components under VCALENDAR.
#[test]
fn zero_components_time() {
    let bytes = fixture_at("collective-icalendar/calendars/time.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

// Malformed parameter syntax.

/// Malformed parameter syntax.
#[test]
fn param_syntax_issue_168_input() {
    let bytes =
        fixture_at("collective-icalendar/calendars/issue_168_input.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Malformed parameter syntax.
#[test]
fn param_syntax_issue_348_exception_parsing_value() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/issue_348_exception_parsing_value.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

// A `VALARM` with `ACTION:DISPLAY` missing `DESCRIPTION` (required, §3.6.6).

/// A VALARM with ACTION:DISPLAY missing DESCRIPTION (required by §3.6.6).
#[test]
fn description_missing_issue_1050_all_components() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/issue_1050_all_components.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

// Invalid UTF-8 / control characters.

/// Invalid UTF-8 / control characters in the input.
#[test]
fn invalid_utf8_issue_1081_invalid_start_valid_end() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/issue_1081_invalid_start_valid_end.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

// A malformed `IMAGE` property value.

/// A malformed IMAGE property value.
#[test]
fn malformed_image_issue_1561_image_value() {
    let bytes =
        fixture_at("collective-icalendar/calendars/issue_1561_image_value.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

// --- issue #27 bucket 3 follow-up: fixtures unblocked by the TZID fix
// (`TimeZoneIdentifier` no longer hard-rejects a non-IANA name) but still
// genuinely invalid for an unrelated reason, now that parsing gets far
// enough to reach it. ---

/// Missing `PRODID` (REQUIRED at `VCALENDAR` level, §3.4) — same shape as
/// the bucket-2 fixtures above, just previously masked by a `TZID` this
/// crate used to hard-reject at parse time.
#[test]
fn prodid_missing_america_new_york() {
    let bytes =
        fixture_at("collective-icalendar/calendars/america_new_york.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing `PRODID` (REQUIRED, §3.4).
#[test]
fn prodid_missing_issue_237_non_ascii_tzid() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/\
         issue_237_fail_to_parse_timezone_with_non_ascii_tzid.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing `PRODID` (REQUIRED, §3.4).
#[test]
fn prodid_missing_issue_466_convert_tzid_with_slash() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/issue_466_convert_tzid_with_slash.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing `PRODID` (REQUIRED, §3.4).
#[test]
fn prodid_missing_issue_466_respect_unique_timezone() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/issue_466_respect_unique_timezone.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing `PRODID` (REQUIRED, §3.4) — also missing `VERSION`/`UID`/
/// `DTSTAMP`, a minimal single-property `DTSTART` excerpt.
#[test]
fn prodid_missing_issue_722_missing_vtimezone_custom() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/issue_722_missing_VTIMEZONE_custom.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing `PRODID` (REQUIRED, §3.4) — also missing `VERSION`/`DTSTAMP`.
#[test]
fn prodid_missing_issue_722_timezone_transition_ambiguity() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/\
         issue_722_timezone_transition_ambiguity.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing `DTSTAMP` (REQUIRED, §3.6.1) on every `VEVENT`.
#[test]
fn dtstamp_missing_issue_313_globally_unique_tzid() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/issue_313_globally_unique_tzid.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Missing `UID` (REQUIRED, §3.8.4.7) on its `VEVENT`.
#[test]
fn uid_missing_issue_165_missing_event() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/issue_165_missing_event.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// `DTSTART` occurs twice on the same `VEVENT` (a singleton property,
/// §3.8.2.4).
#[test]
fn duplicate_dtstart_america_new_york_forward_reference() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/america_new_york_forward_reference.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// `DTSTART` occurs twice on the same `VEVENT` (a singleton property,
/// §3.8.2.4).
#[test]
fn duplicate_dtstart_pacific_fiji() {
    let bytes = fixture_at("collective-icalendar/calendars/pacific_fiji.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// `DTSTART;TZID=America/New_York` paired with
/// `RDATE;TZID="Central Standard Time"` — two different spellings for what
/// is likely the same real-world zone, but this crate has no Windows/IANA
/// alias table to prove that (see issue #6's `TZID` cross-check, extended
/// from just value-type matching).
#[test]
fn rdate_tzid_mismatch_issue_156_khal() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/issue_156_RDATE_with_PERIOD_TZID_khal.\
         ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// `STATUS:Confirmed` — not the uppercase token RFC 5545 §3.8.1.11 defines
/// (`CONFIRMED`). This crate matches `STATUS` and every other enumerated
/// RFC 5545 token case-sensitively, consistently, so this isn't
/// specifically tolerated.
#[test]
fn status_value_not_uppercase_issue_218_bad_tzid() {
    let bytes =
        fixture_at("collective-icalendar/calendars/issue_218_bad_tzid.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// `SUMMARY=testevent` — `=` instead of `:` introducing the property value.
#[test]
fn malformed_property_syntax_timezone_rdate() {
    let bytes = fixture_at("collective-icalendar/calendars/timezone_rdate.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// `END:VCALENDARD` — a typo'd component-close keyword, so `END` doesn't
/// match `BEGIN:VCALENDAR`.
#[test]
fn end_name_typo_timezone_same_start_and_offset() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/timezone_same_start_and_offset.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// `DTSTAR` (missing the trailing `T`) instead of `DTSTART`, on both the
/// `VEVENT` and inside `VTIMEZONE`'s `DAYLIGHT` sub-component — an
/// unrecognized property name, so it falls back to the `Iana`/`Xprop`
/// catch-all rather than ever setting the real `DTSTART` field.
#[test]
fn dtstart_typo_libical_1() {
    let bytes = fixture_at("libical/1.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

// --- issue #27 bucket 4: the remaining, previously untriaged failures ---

/// `SUMMARY` occurs twice on the same `VEVENT` (a singleton property,
/// §3.8.7.2) — the second copy is folded across two physical lines but has
/// (coincidentally) identical text to the first.
#[test]
fn duplicate_summary_libical_0() {
    let bytes = fixture_at("libical/0.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// `RDATE;VALUE=TIME:...` — `TIME` isn't a legal `RDATE` value type per
/// §3.8.5.2's grammar (`rdtval = date-time / date / period`, no `TIME`
/// alternative); parsed as a malformed `DATE` instead (the byte shape
/// `083000` has neither `/` nor `T`), which surfaces as a confusing but
/// still-correct "input is out of range" (an invalid month/day) rather than
/// a clearer "unsupported VALUE" message.
#[test]
fn rdate_value_time_is_not_a_legal_value_type() {
    let bytes =
        fixture_at("collective-icalendar/calendars/multiple_timezones.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A property name immediately followed by an empty physical line, then a
/// `SP`-prefixed continuation (`VERSION\r\n\r\n :2.0\r\n`). RFC 5545's
/// fold-removal rule operates on raw bytes — "any CRLF immediately followed
/// by a single SP/HTAB is removed" — with no concept of "logical line", so
/// this crate's (correct) mechanical unfolding collapses the *second* CRLF
/// (the empty line's own terminator, which happens to be followed by a SP)
/// into the following `:2.0`, leaving `VERSION` orphaned on its own logical
/// line and `:2.0` starting a new one with no property name. Confirms this
/// is a `Lexer` error (an empty NAME token), not evidence of a bug in
/// `unfold` itself — see `src/ast/lexer/unfold.rs`'s own unit tests for
/// unfolding's well-behaved cases.
#[test]
fn blank_line_before_fold_continuation_orphans_the_property_name() {
    let bytes = fixture_at(
        "collective-icalendar/calendars/multiple_calendar_components.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Lexer(_))
    ));
}

/// Deliberately malformed component-property-at-calendar-level torture
/// tests from the libical suite (`DURATION`/`SUMMARY`/`DTSTART`/etc.
/// appearing directly under `VCALENDAR`, never inside any component) — same
/// "unrecognized/misplaced property" shape as `fuzz_testcase_invalid_month.\
/// ics` above, just larger.
#[test]
fn component_properties_directly_under_vcalendar_libical_1_1() {
    let bytes = fixture_at("libical/1-1.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Same shape as above, a much larger torture test with duplicated params,
/// garbage values, and misplaced component properties throughout.
#[test]
fn component_properties_directly_under_vcalendar_stresstest() {
    let bytes = fixture_at("libical/stresstest.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Fuzzer-mutated garbage (control bytes, NUL/high bytes injected
/// mid-token, garbled component/parameter names, lone `CR`s) — the same
/// "fuzzer-discovered crash corpus" style `tests/fixtures/libical-fuzz-\
/// corpus/` already holds, just living under `libical/` proper. Only
/// required not to panic, like that corpus — an exact error variant isn't
/// meaningful for adversarial byte noise, so these match broadly rather
/// than pinning `Lexer`/`Parse`.
#[test]
fn fuzzer_mutated_garbage_does_not_panic() {
    for name in [
        "crash.ics",
        "get_char_test.ics",
        "issue250.ics",
        "issue251.ics",
        "issue252.ics",
        "issue253.ics",
        "malloc.ics",
        "caltime.ics",
        "zday.ics",
    ] {
        let bytes = fixture_at(&format!("libical/{name}"));
        assert!(
            Calendar::parse(&bytes).is_err(),
            "{name} should be rejected, not silently accepted"
        );
    }
}
