//! Regression coverage for two distinct sets of "real-world-valid, but
//! `Calendar::parse` still returns `Err`" fixtures, both excluded from the
//! blanket "must parse successfully" fixture tests generated by `build.rs`
//! (see `OUT_OF_SCOPE_FIXTURES` there):
//!
//! - The scope decisions in issues #7 and #17: this crate targets RFC 5545
//!   core, plus `VAVAILABILITY` (RFC 7953, added under the `rfc_7953` feature —
//!   see issue #16) and `VLOCATION`/the RFC 9074 `VALARM` extensions (`UID`,
//!   `RELATED-TO`, `ACKNOWLEDGED`, `PROXIMITY`, added under the `rfc_9074`
//!   feature — see issue #17). See `src/components.rs`'s module doc. Every
//!   fixture in this group still returns `Err` even though the
//!   component/properties it exercises are now supported — see each test's own
//!   doc for why (a bare component excerpt with no `VCALENDAR` wrapper, or one
//!   missing `PRODID`/ `VERSION`), unrelated to whether this crate implements
//!   what the fixture contains. Real parsing coverage lives in
//!   `tests/rfc_7953.rs`/`tests/rfc_9074.rs`.
//! - Issue #27 bucket 1: a much larger set of real-world fixtures (from the
//!   collective-icalendar and libical corpora) that are bare component excerpts
//!   with no `BEGIN:VCALENDAR`/`END:VCALENDAR` wrapper at all —
//!   `Calendar::parse` requires a full `icalobject`, so these fail before
//!   parsing ever reaches whatever component/property the fixture is actually
//!   demonstrating, regardless of whether this crate implements it. Not tied to
//!   any particular RFC feature's scope.
//!
//! Each test below pins down that `Calendar::parse` currently returns `Err`
//! for its fixture — not proof that the component itself is rejected, just
//! that the fixture isn't silently mistaken for coverage of something it
//! doesn't actually exercise.

use icalendar::{Calendar, CalendarParseError};

fn fixture(rel: &str) -> Vec<u8> {
    let path = format!(
        "{}/tests/fixtures/collective-icalendar/{rel}",
        env!("CARGO_MANIFEST_DIR")
    );
    std::fs::read(&path)
        .unwrap_or_else(|e| panic!("fixture {rel} should be readable: {e}"))
}

/// A bare `VAVAILABILITY` excerpt (RFC 7953 §3.1's first example) with no
/// `BEGIN:VCALENDAR` wrapper — still an `Err`, but because `Calendar::parse`
/// requires a full `icalobject`, not because `VAVAILABILITY` is
/// unsupported. See `tests/rfc_7953.rs` for this same example wrapped in a
/// minimal `VCALENDAR`, where it parses successfully.
#[test]
fn vavailability_example_1_is_not_a_full_calendar_object() {
    let bytes = fixture("availabilities/rfc_7953_1.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Same shape as above (RFC 7953 §3.1's second example): bare
/// `VAVAILABILITY`, no `VCALENDAR` wrapper.
#[test]
fn vavailability_example_2_is_not_a_full_calendar_object() {
    let bytes = fixture("availabilities/rfc_7953_2.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// This one *is* wrapped in `BEGIN:VCALENDAR`/`END:VCALENDAR`, and its three
/// top-level `VAVAILABILITY` components each parse as real
/// `Component::Availability` values — but the fixture itself is missing the
/// calendar-level `PRODID`/`VERSION` properties RFC 5545 §3.4 requires, so
/// `CalendarBuilder::build` still rejects it. Still an `Err`, for a reason
/// unrelated to `VAVAILABILITY` support.
#[test]
fn vavailability_example_3_missing_prodid_and_version() {
    let bytes = fixture("calendars/rfc_7953_3.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT`/`VALARM` excerpt (RFC 9074 §6's first example) — no
/// `VCALENDAR` wrapper, so it can't be fed to `Calendar::parse` as-is even
/// though its `VALARM`'s `UID`/`ACKNOWLEDGED` are supported under the
/// `rfc_9074` feature. See `tests/rfc_9074.rs` for this same example
/// wrapped in a minimal `VCALENDAR`, where it parses successfully.
#[test]
fn rfc_9074_example_1_is_not_a_full_calendar_object() {
    let bytes = fixture("events/rfc_9074_example_1.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Same shape (RFC 9074 §6's second example).
#[test]
fn rfc_9074_example_2_is_not_a_full_calendar_object() {
    let bytes = fixture("events/rfc_9074_example_2.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Same shape (RFC 9074 §6's third example).
#[test]
fn rfc_9074_example_3_is_not_a_full_calendar_object() {
    let bytes = fixture("events/rfc_9074_example_3.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Same shape (RFC 9074 §6's fourth example).
#[test]
fn rfc_9074_example_4_is_not_a_full_calendar_object() {
    let bytes = fixture("events/rfc_9074_example_4.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// RFC 9074's `PROXIMITY` `VALARM` extension example (RFC 9074 §8.2) — a
/// `VALARM` with a nested `VLOCATION` (RFC 9073 §7.2). No `VCALENDAR`
/// wrapper, so still an `Err`, even though `PROXIMITY`/`VLOCATION` are
/// supported under the `rfc_9074` feature.
#[test]
fn rfc_9074_proximity_example_is_not_a_full_calendar_object() {
    let bytes = fixture("events/rfc_9074_example_proximity.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

// --- issue #27 bucket 1: bare component excerpts, no VCALENDAR wrapper ---
//
// These are real-world fixtures (from the collective-icalendar and libical
// corpora) that are perfectly valid as component excerpts, but none of them
// is wrapped in `BEGIN:VCALENDAR`/`END:VCALENDAR` -- `Calendar::parse`
// requires a full `icalobject` (RFC 5545 grammar's `icalstream`), so every
// one of these is an `Err` for that structural reason alone, unrelated to
// whether this crate implements the component/properties inside.

/// A bare `VALARM` excerpt
/// (`alarms/example.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_alarms_example() {
    let bytes = fixture("alarms/example.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VALARM` excerpt
/// (`alarms/rfc_5545_absolute_alarm_example.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_alarms_rfc_5545_absolute_alarm_example() {
    let bytes = fixture("alarms/rfc_5545_absolute_alarm_example.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VALARM` excerpt
/// (`alarms/rfc_5545_end.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_alarms_rfc_5545_end() {
    let bytes = fixture("alarms/rfc_5545_end.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VALARM` excerpt
/// (`alarms/start_date.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_alarms_start_date() {
    let bytes = fixture("alarms/start_date.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VFREEBUSY` excerpt
/// (`freebusy/example.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_freebusy_example() {
    let bytes = fixture("freebusy/example.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VJOURNAL` excerpt
/// (`journals/example.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_journals_example() {
    let bytes = fixture("journals/example.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VTIMEZONE` excerpt
/// (`timezones/issue_237_brazilia_standard.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_timezones_issue_237_brazilia_standard() {
    let bytes = fixture("timezones/issue_237_brazilia_standard.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VTIMEZONE` excerpt
/// (`timezones/issue_53_tzid_parsed_properly.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_timezones_issue_53_tzid_parsed_properly() {
    let bytes = fixture("timezones/issue_53_tzid_parsed_properly.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VTIMEZONE` excerpt
/// (`timezones/issue_55_parse_error_on_utc_offset_with_seconds.ics`), no
/// `VCALENDAR` wrapper.
#[test]
fn out_of_scope_timezones_issue_55_parse_error_on_utc_offset_with_seconds() {
    let bytes = fixture(
        "timezones/issue_55_parse_error_on_utc_offset_with_seconds.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VTIMEZONE` excerpt
/// (`timezones/pacific_fiji.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_timezones_pacific_fiji() {
    let bytes = fixture("timezones/pacific_fiji.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VTODO` excerpt
/// (`todos/example.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_todos_example() {
    let bytes = fixture("todos/example.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT` excerpt
/// (`events/event_with_escaped_character1.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_events_event_with_escaped_character1() {
    let bytes = fixture("events/event_with_escaped_character1.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT` excerpt
/// (`events/event_with_escaped_character2.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_events_event_with_escaped_character2() {
    let bytes = fixture("events/event_with_escaped_character2.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT` excerpt
/// (`events/event_with_escaped_character3.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_events_event_with_escaped_character3() {
    let bytes = fixture("events/event_with_escaped_character3.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT` excerpt
/// (`events/event_with_escaped_character4.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_events_event_with_escaped_character4() {
    let bytes = fixture("events/event_with_escaped_character4.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT` excerpt
/// (`events/event_with_escaped_characters.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_events_event_with_escaped_characters() {
    let bytes = fixture("events/event_with_escaped_characters.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT` excerpt
/// (`events/event_with_recurrence.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_events_event_with_recurrence() {
    let bytes = fixture("events/event_with_recurrence.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT` excerpt
/// (`events/event_with_recurrence_exdates_on_different_lines.ics`), no
/// `VCALENDAR` wrapper.
#[test]
fn out_of_scope_events_event_with_recurrence_exdates_on_different_lines() {
    let bytes =
        fixture("events/event_with_recurrence_exdates_on_different_lines.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT` excerpt
/// (`events/event_with_rsvp.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_events_event_with_rsvp() {
    let bytes = fixture("events/event_with_rsvp.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT` excerpt
/// (`events/event_with_unicode_fields.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_events_event_with_unicode_fields() {
    let bytes = fixture("events/event_with_unicode_fields.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT` excerpt
/// (`events/event_with_unicode_organizer.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_events_event_with_unicode_organizer() {
    let bytes = fixture("events/event_with_unicode_organizer.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT` excerpt
/// (`events/issue_100_transformed_doctests_into_unittests.ics`), no `VCALENDAR`
/// wrapper.
#[test]
fn out_of_scope_events_issue_100_transformed_doctests_into_unittests() {
    let bytes =
        fixture("events/issue_100_transformed_doctests_into_unittests.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT` excerpt
/// (`events/issue_101_icalendar_chokes_on_umlauts_in_organizer.ics`), no
/// `VCALENDAR` wrapper.
#[test]
fn out_of_scope_events_issue_101_icalendar_chokes_on_umlauts_in_organizer() {
    let bytes = fixture(
        "events/issue_101_icalendar_chokes_on_umlauts_in_organizer.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT` excerpt
/// (`events/issue_104_mark_events_broken.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_events_issue_104_mark_events_broken() {
    let bytes = fixture("events/issue_104_mark_events_broken.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT` excerpt
/// (`events/issue_112_missing_tzinfo_on_exdate.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_events_issue_112_missing_tzinfo_on_exdate() {
    let bytes = fixture("events/issue_112_missing_tzinfo_on_exdate.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT` excerpt
/// (`events/issue_156_RDATE_with_PERIOD.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_events_issue_156_rdate_with_period() {
    let bytes = fixture("events/issue_156_RDATE_with_PERIOD.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT` excerpt
/// (`events/issue_156_RDATE_with_PERIOD_list.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_events_issue_156_rdate_with_period_list() {
    let bytes = fixture("events/issue_156_RDATE_with_PERIOD_list.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT` excerpt
/// (`events/issue_157_removes_trailing_semicolon.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_events_issue_157_removes_trailing_semicolon() {
    let bytes = fixture("events/issue_157_removes_trailing_semicolon.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT` excerpt
/// (`events/issue_184_broken_representation_of_period.ics`), no `VCALENDAR`
/// wrapper.
#[test]
fn out_of_scope_events_issue_184_broken_representation_of_period() {
    let bytes = fixture("events/issue_184_broken_representation_of_period.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT` excerpt
/// (`events/issue_355_url_escaping.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_events_issue_355_url_escaping() {
    let bytes = fixture("events/issue_355_url_escaping.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT` excerpt
/// (`events/issue_355_url_escaping_2.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_events_issue_355_url_escaping_2() {
    let bytes = fixture("events/issue_355_url_escaping_2.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT` excerpt
/// (`events/issue_355_url_escaping_empty_param.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_events_issue_355_url_escaping_empty_param() {
    let bytes = fixture("events/issue_355_url_escaping_empty_param.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT` excerpt
/// (`events/issue_464_invalid_rdate.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_events_issue_464_invalid_rdate() {
    let bytes = fixture("events/issue_464_invalid_rdate.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT` excerpt
/// (`events/issue_53_description_parsed_properly.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_events_issue_53_description_parsed_properly() {
    let bytes = fixture("events/issue_53_description_parsed_properly.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT` excerpt
/// (`events/issue_64_event_with_ascii_summary.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_events_issue_64_event_with_ascii_summary() {
    let bytes = fixture("events/issue_64_event_with_ascii_summary.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT` excerpt
/// (`events/issue_64_event_with_non_ascii_summary.ics`), no `VCALENDAR`
/// wrapper.
#[test]
fn out_of_scope_events_issue_64_event_with_non_ascii_summary() {
    let bytes = fixture("events/issue_64_event_with_non_ascii_summary.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT` excerpt
/// (`events/issue_70_rrule_causes_attribute_error.ics`), no `VCALENDAR`
/// wrapper.
#[test]
fn out_of_scope_events_issue_70_rrule_causes_attribute_error() {
    let bytes = fixture("events/issue_70_rrule_causes_attribute_error.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT` excerpt
/// (`events/issue_82_expected_output.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_events_issue_82_expected_output() {
    let bytes = fixture("events/issue_82_expected_output.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT` excerpt
/// (`events/rfc_7265_example_4.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_events_rfc_7265_example_4() {
    let bytes = fixture("events/rfc_7265_example_4.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT` excerpt
/// (`events/rfc_7265_request_status.ics`), no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_events_rfc_7265_request_status() {
    let bytes = fixture("events/rfc_7265_request_status.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

// A couple of `collective-icalendar/calendars/` fixtures that are also bare
// excerpts despite living in the `calendars/` directory.

/// An unrecognized/custom top-level component name, with no
/// `VCALENDAR` wrapper.
#[test]
fn out_of_scope_calendars_issue_178_component_with_invalid_name_represented() {
    let bytes = fixture(
        "calendars/issue_178_component_with_invalid_name_represented.ics",
    );
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A custom top-level component nesting another component, with
/// no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_calendars_issue_178_custom_component_contains_other() {
    let bytes =
        fixture("calendars/issue_178_custom_component_contains_other.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare component excerpt, no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_calendars_issue_82_expected_output() {
    let bytes = fixture("calendars/issue_82_expected_output.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

// --- libical/ bare excerpts ---

/// A bare component excerpt from the libical test suite, no
/// `VCALENDAR` wrapper.
#[test]
fn out_of_scope_libical_8() {
    let path = format!(
        "{}/tests/fixtures/libical/8.ics",
        env!("CARGO_MANIFEST_DIR")
    );
    let bytes = std::fs::read(&path)
        .unwrap_or_else(|e| panic!("fixture 8.ics should be readable: {e}"));
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// `BEGIN:VCARD` -- not even an iCalendar object (a vCard, RFC
/// 6350), let alone one with a `VCALENDAR` wrapper.
#[test]
fn out_of_scope_libical_issue339() {
    let path = format!(
        "{}/tests/fixtures/libical/issue339.ics",
        env!("CARGO_MANIFEST_DIR")
    );
    let bytes = std::fs::read(&path).unwrap_or_else(|e| {
        panic!("fixture issue339.ics should be readable: {e}")
    });
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Five bare sibling `VEVENT`s, still with no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_libical_overlaps() {
    let path = format!(
        "{}/tests/fixtures/libical/overlaps.ics",
        env!("CARGO_MANIFEST_DIR")
    );
    let bytes = std::fs::read(&path).unwrap_or_else(|e| {
        panic!("fixture overlaps.ics should be readable: {e}")
    });
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare component excerpt exercising recurrence-rule edge
/// cases, no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_libical_recur_errors() {
    let path = format!(
        "{}/tests/fixtures/libical/recur-errors.ics",
        env!("CARGO_MANIFEST_DIR")
    );
    let bytes = std::fs::read(&path).unwrap_or_else(|e| {
        panic!("fixture recur-errors.ics should be readable: {e}")
    });
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare component excerpt, no `VCALENDAR` wrapper.
#[test]
fn out_of_scope_libical_spanlist() {
    let path = format!(
        "{}/tests/fixtures/libical/spanlist.ics",
        env!("CARGO_MANIFEST_DIR")
    );
    let bytes = std::fs::read(&path).unwrap_or_else(|e| {
        panic!("fixture spanlist.ics should be readable: {e}")
    });
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A fully-formed, otherwise-valid calendar using RFC 7529's `RSCALE`
/// (non-Gregorian recurrence), which this crate doesn't implement at all
/// (see the README's "Not yet implemented" section). Still an `Err`, but on
/// content rather than structure — unlike the bare excerpts above.
#[test]
fn out_of_scope_rfc_7529_rscale_not_implemented() {
    let bytes = fixture("calendars/rfc_7529.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}
