//! Regression coverage for the scope decision in issue #7: this crate
//! targets RFC 5545 core, plus `VAVAILABILITY` (RFC 7953, added under the
//! `rfc_7953` feature — see issue #16). `VLOCATION` (RFC 9073, nested
//! inside `VALARM`) and the RFC 9074 `VALARM` extensions (`UID`,
//! `PROXIMITY`, `ACKNOWLEDGED`) remain deliberately not implemented — see
//! `src/components.rs`'s module doc.
//!
//! The `VAVAILABILITY` fixtures below still return `Err` from
//! `Calendar::parse` even though the component itself is now supported —
//! see each test's own doc for why (a bare component excerpt with no
//! `VCALENDAR` wrapper, or one missing `PRODID`/`VERSION`), which is
//! unrelated to `VAVAILABILITY` support. Real `VAVAILABILITY` parsing
//! coverage lives in `tests/rfc_7953.rs`.
//!
//! Every fixture used here is real-world-valid for the RFC it demonstrates,
//! but exercises a component/property this crate doesn't model, so it's
//! excluded from the blanket "must parse successfully" fixture tests
//! generated by `build.rs` (see `OUT_OF_SCOPE_FIXTURES` there). Each test
//! below pins down that `Calendar::parse` currently returns `Err` for it —
//! not proof that the component itself is rejected (most of these fixtures
//! are bare RFC-example excerpts with no `BEGIN:VCALENDAR` wrapper at all,
//! so they'd fail before parsing ever reached the unimplemented
//! component/property), just that the fixture isn't silently mistaken for
//! coverage of something this crate doesn't implement.

use icalendar::{Calendar, CalendarParseError};

fn fixture(rel: &str) -> Vec<u8> {
    let path = format!(
        "{}/tests/fixtures/collective-icalendar/{rel}",
        env!("CARGO_MANIFEST_DIR")
    );
    std::fs::read(&path)
        .unwrap_or_else(|e| panic!("fixture {rel} should be readable: {e}"))
}

/// A bare `VAVAILABILITY` excerpt (RFC 7953 §3.1's first example) with no
/// `BEGIN:VCALENDAR` wrapper — still an `Err`, but because `Calendar::parse`
/// requires a full `icalobject`, not because `VAVAILABILITY` is
/// unsupported. See `tests/rfc_7953.rs` for this same example wrapped in a
/// minimal `VCALENDAR`, where it parses successfully.
#[test]
fn vavailability_example_1_is_not_a_full_calendar_object() {
    let bytes = fixture("availabilities/rfc_7953_1.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Same shape as above (RFC 7953 §3.1's second example): bare
/// `VAVAILABILITY`, no `VCALENDAR` wrapper.
#[test]
fn vavailability_example_2_is_not_a_full_calendar_object() {
    let bytes = fixture("availabilities/rfc_7953_2.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// This one *is* wrapped in `BEGIN:VCALENDAR`/`END:VCALENDAR`, and its three
/// top-level `VAVAILABILITY` components each parse as real
/// `Component::Availability` values — but the fixture itself is missing the
/// calendar-level `PRODID`/`VERSION` properties RFC 5545 §3.4 requires, so
/// `CalendarBuilder::build` still rejects it. Still an `Err`, for a reason
/// unrelated to `VAVAILABILITY` support.
#[test]
fn vavailability_example_3_missing_prodid_and_version() {
    let bytes = fixture("calendars/rfc_7953_3.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// A bare `VEVENT`/`VALARM` excerpt (RFC 9074 §6's first example) — no
/// `VCALENDAR` wrapper, and the `VALARM` carries an RFC 9074 `UID` this
/// crate's `AlarmBuilder` doesn't model as a dedicated property.
#[test]
fn rfc_9074_example_1_is_not_a_full_calendar_object() {
    let bytes = fixture("events/rfc_9074_example_1.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// Same shape (RFC 9074 §6's second example).
#[test]
fn rfc_9074_example_2_is_not_a_full_calendar_object() {
    let bytes = fixture("events/rfc_9074_example_2.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// RFC 9074 §6's third example — a `VALARM` with a nested `VLOCATION` (RFC
/// 9073), which isn't a component this crate's `AlarmBuilder` recognizes.
#[test]
fn rfc_9074_example_3_is_not_a_full_calendar_object() {
    let bytes = fixture("events/rfc_9074_example_3.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// RFC 9074 §6's fourth example.
#[test]
fn rfc_9074_example_4_is_not_a_full_calendar_object() {
    let bytes = fixture("events/rfc_9074_example_4.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}

/// RFC 9074's `PROXIMITY` `VALARM` extension example.
#[test]
fn rfc_9074_proximity_example_is_not_a_full_calendar_object() {
    let bytes = fixture("events/rfc_9074_example_proximity.ics");
    assert!(matches!(
        Calendar::parse(&bytes),
        Err(CalendarParseError::Parse(_))
    ));
}
